/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/myra.glb -o src/components/MyraModel.tsx 
Author: Kiddo Acosta (https://sketchfab.com/Hermes.Waterlow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mika-melatika-from-nijisanji-alt-outfit-bcb84e42798a4f55ac2a763c27591cf0
Title: Mika Melatika from nijisanji (alt outfit)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    new_mika_skin: THREE.MeshBasicMaterial
    new_mika_hair_and_clothes: THREE.MeshBasicMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/myra.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.new_mika_skin} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.new_mika_hair_and_clothes} skeleton={nodes.Object_8.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/myra.glb')
